// Mythic Crucible — BG3 Modlist PDF
// Generated by build.bat via scripts/convert.js

#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 2cm, right: 2cm),
  numbering: "1",
  number-align: center,
)

#set page(fill: rgb("#1a1220"))

#set text(
  font: ("Times New Roman"),
  size: 12pt,
  fill: rgb("#e8dcc8"),
)

#show heading: set text(
  fill: rgb("#d4a843"),
)

#show link: underline

// ===== COVER PAGE =====
#align(center)[
  #v(4cm)
  #image("assets/logo.jpg", width: 6cm)
  #v(1cm)
  #text(size: 28pt, weight: "bold", fill: rgb("#d4a843"))[Mythic Crucible]
  #v(0.5cm)
  #text(size: 14pt, fill: rgb("#c0b090"))[A Baldur's Gate 3 Modlist & Guide]
  #v(0.3cm)
  #text(size: 10pt, fill: rgb("#8a7a60"))[Patch 8 / Hotfix #36 — April 2025]
  #v(0.5cm)
  #text(size: 10pt, fill: rgb("#8a7a60"))[BG3 Mod Manager (BG3MM)]
  #v(2cm)
  #text(size: 11pt, fill: rgb("#a09078"))[Curated by Emperor Jimmu]
]

#pagebreak()

// ===== TABLE OF CONTENTS =====
#outline(
  title: [Table of Contents],
  depth: 2,
)

#pagebreak()

// ===== CONTENT =====
// Content loaded from pre-converted .typ files in guide/.typst-cache/
// The convert.js script produces these from guide/*.md

#include "guide/.typst-cache/00-cover.typ"
#pagebreak()
#include "guide/.typst-cache/01-installation.typ"
#pagebreak()
#include "guide/.typst-cache/02-wave-0-guide.typ"
#pagebreak()
#include "guide/.typst-cache/03-wave-0-modlist.typ"
#pagebreak()
#include "guide/.typst-cache/04-wave-1-guide.typ"
#pagebreak()
#include "guide/.typst-cache/05-wave-1-modlist.typ"
#pagebreak()
#include "guide/.typst-cache/06-load-order.typ"
