#let callout(title, body) = block(
  fill: rgb("#f7e8d8"), inset: 8pt, radius: 4pt,
  stroke: 0.5pt + rgb("#d97b3a"),
)[*#title* #body]

== The Expedition: Strategy

Wave 2 ended with a forge, a wall and a faction that could arm itself. Wave 3 is what that strength is *for*: leaving the walls behind and going where the map stops being theory. This is the chapter for the road — how to plan a journey that lasts weeks instead of days, how to read the hazards each biome puts in your path, how the world itself shifts as its leaders die, and how to turn the wilderness into recruits, loot and story. The mods in this wave make the road deeper, not safer; every card in the mod sections exists to give the journey a reason, never to shorten it.

The single most important thing to internalise is that in Kenshi, *the map is a promise, and the expedition is how you collect on it*. The game's world is enormous, dangerous and deliberately indifferent to you — but it is also *knowable*. Zones have rules: where acid rains, where gas pools, where the Beak Things nest, which factions patrol which roads, and which of those patrols vanish when their leaders die. A squad that reads the land can cross half the continent; a squad that ignores it dies in a swamp with full food. Wave 3's mods put more land under those rules — more zones, more recruits, more places worth reaching — and the strategy is learning to read them.

#callout("Warning:", [Do not treat the expedition as a vacation from the base. The outpost you built in Waves 1 and 2 is the expedition's supplier, not its destination: it grows the food, forges the weapons and holds the surplus that a long journey burns through. Leave with an empty storehouse and you will be back in a week, poorer. The expedition and the outpost are one economy, not two.])
 
=== Planning the Long Expedition

Every great journey in Kenshi fails the same way: someone runs out of something the map will not sell. Food, medicine, replacement limbs and an escape route are the four loads a serious expedition packs, and each one has a wiki-verified rule behind it.

*Food.* The campfire is the expedition's kitchen. The wiki's Camping page confirms the vanilla structures: Flat Shelter, Mercenary Tent, Scrap Tent, Camp Bed and Campfire — all temporary buildings that cost nothing to claim land for. Cooking turns raw meat and vegetables into cooked meals that last far longer in a pack, and the longer you stay out, the more the cooking pit (Sensible Nomadism) and the tent shelter (Tents) matter: both are the difference between sleeping under the sky and sleeping under cover while the rain does its work. Pack food for the journey *out* and plan to hunt and cook on the way *back* — wild game is everywhere, but cooking it requires fuel, time and a safe patch of ground, so the return leg is the one that rewards camping.

*Medicine.* The wiki's Guide to Health is specific about the split: organic characters heal with First Aid Kits, but *Skeletons and robot limbs need a Skeleton Repair Kit* (or its Authentic variant) instead — the game literally relabels the action "Repairs" for them. Kits are found in stores, looted from skeletons, and stocked in Ancient Labs. An expedition into skeleton territory with no repair kits is an expedition that watches its heaviest hitters fall to scrap damage that nothing can fix. Pack for the *species* of your squad, not for a generic wound.

#callout("Tip:", [The replaceable-squad theory of medicine. No expedition can carry enough kits to save everyone; the realistic plan is to protect the irreplaceable (your smith, your unique recruits, your limbs-bearing veterans) and let casualties fall on the replaceable. Before you leave, decide who the expedition cannot lose — then put the repair kits and the best armour on them.])
 
*Replacement limbs.* The wiki's Robot Limbs page is blunt about where limbs come from: Hive Robotics Shop (cheapest), Mongrel Robotics Workshop, the Robotics Shop in Black Desert City (the largest high-quality selection in the game), and the Travel and Repairs shops that dot the map. Limbs have real tradeoffs — bonuses and penalties to specific skills — so a Masterwork limb is a genuine asset, not a cosmetic. The strategy implication is spatial: if the expedition's journey crosses a limb shop, that is where you repair your veterans and upgrade your wounded. If it does not, an amputated fighter is a permanent downgrade for the rest of the trip.

*Escape routes.* The last load is the one nobody packs. Every biome worth visiting is also home to something that can kill a squad outright, and the expedition's exit must be decided *before* the thing appears, not after. This is where the camping mods stop being convenience and become survival: Tents deploy anywhere without claiming land, and the wiki confirms they heal at Camp Bed rate with partial acid-rain protection — so a 1x tent is a mobile safe-zone that can shelter a wounded squad member while the fight is lost and the retreat is on. Sensible Nomadism's Landmark turns a chosen map point into a named, remembered waypoint — the strategic half of an escape route is *knowing where you are going to fall back to*.

#callout("Warning:", [Food is the silent expedition-killer. Cooked food rots on a timer, and the wiki is explicit that the longer you stay in the field, the more your pack degrades. Plan journeys as loops that return to food: out, hunt, cook, sleep under a tent, hunt again, return. A squad that tries to carry two weeks of raw supplies instead of living off the land is carrying dead weight it will run out of at the worst possible moment.])
 
=== Biome Navigation: Acid, Gas, Sand and Beak Things

Kenshi's biomes are not scenery; they are a set of hazards with hard rules, and the wiki's Weather Effects page is the map. The acid-rain zones alone are a list: Burning Forest (acid only during its acid-forest season), Darkfinger, Deadlands, Iron Valleys, Howler Maze, Sonorous Dark, The Iron Trail, The Pits and its East, The Unwanted Zone, Islands of None, Northern Coast, Leviathan Coast, Royal Valley and Greyshelf. The Deadlands page adds the tone: *constant* acid rain, acidic ground, dark weather, a dead environment — and the home of the Skeletons faction in Black Desert City. Walking into the Deadlands without acid-rain protection is not a mistake; it is a death sentence with a longer timeline.

The exceptions matter as much as the rules. Vain, famously, is *not* an acid-rain zone: the wiki's Vain page is explicit that "although it is red, the rain isn't acidic... However, the bodies of water are." So the Western Hive heartland is safe to walk in the open but lethal to wade into — a distinction that has killed more than one expedition that assumed red equals acid everywhere. The Ashlands, per the wiki, add a second hazard on top of their poisoned air: *large clouds of poison gas* that require a Fog Mask to pass, over a landscape patrolled by the Second Empire's Skeleton Legion and Iron Spiders. The far southeast is the expedition's endgame, and the endgame suffocates you if you are not equipped for it.

#callout("Tip:", [The acid-rain readout is per-squad, not per-region. Acid rain only harms organic characters exposed to it — skeletons shrug it off, and a squad of robots can cross the Deadlands the way organic squads cross the Border Zone. If the expedition must pass an acid zone, split the difference: send the skeleton escort through the rain while the organics wait under cover, or bring the acid-proof equipment and tents that Tents provides. Read your roster before you read the weather.])
 
Dust storms and sandstorms run the same geography. The wiki's weather list puts them in the Border Zone, Shun, The Great Desert, The Hook, Stenn Desert, Purple Sands, Skinner's Roam, The Crags, The Pits and Burning Forest. Sandstorms cut visibility hard — ranged attackers lose their accuracy window, and Beak Things use the noise to close in. The Great Desert, home of the UC capital Heft and the towns Stoat, Sho-Battai and Bark, is the classic sandstorm zone: it is *the* trade corridor of the map and also the place where the Skimmers hunt the dunes and the caravan lines run deepest. Navigating it is an exercise in patience — move on the roads, keep your ranged units from committing shots into a sandstorm, and accept that some days the weather owns the road.

And then there are the Beak Things. The wiki's Beak Thing page is the expedition's required reading, because it lists the seven core regions where they nest: Leviathan Coast (with migrations reaching Cannibal Plains and Purple Sands), Gut and The Unwanted Zone (migrations to Stormgap Coast, Venge and Shem), the Bonefields (migrations to High Bonefields and Flats Lagoon), Vain, The Crater and Greenbeach. The warning is unambiguous: they "run extremely fast, hit hard, and will eat incapacitated organic prey whether dead or not." Elder Beak Things spawn in the High Bonefields. A nest spawns one to thirty Beak Thing Eggs. There is no biome in Kenshi whose rules you should memorise more carefully than the one that says *do not go down within their reach*.

#callout("Warning:", [Beak Things are the expedition's boss fight, and the fight is *leaving*. They are faster than a standard squad on the open ground, and the wiki's description is blunt — incapacitated prey gets eaten alive. The counter is not outrunning them in a straight line; it is terrain: chokepoints, buildings, the cover of a deployable tent, a mounted turret carried by the Portable kit from Wave 2. Plan every Gut crossing around a fallback point, and never let a squad member go down while the pack is still on the field — the moment someone is downed and the Beak Things close, the priority stops being winning and becomes *dragging that body to cover*.])
 
=== World States: How the World Changes Around You

The expedition crosses territory that is actively changing, and the wiki's World States page explains the mechanism: killing or kidnapping the important leader(s) of a faction *reduces that faction's squad spawn rates* in the regions it controls, and if a faction's base is taken over, it is destroyed or occupied by a different faction. The conditions are stricter than they sound — imprisoning a leader counts as killing for most world-state purposes, but "alive" conditions mean alive *and free*, so a captured-but-breathing leader still triggers death states. This is the world's central dynamic, and the expedition is when you start to feel it.

The classic example is the Holy Nation, and the wiki's Border Zone page makes the dependency explicit: the Holy Army Patrol's behaviour shifts with which leaders are dead and which are alive (Seto dead and Phoenix alive, Esata dead and Phoenix alive, and so on). When the Phoenix, Valtena and Seta are all dead, the Holy Nation's regular patrols are overridden by the Holy Army Bandits and the Diaspora of Strayed Paladins. The same logic governs the Southern and United Cities: The Great Desert page notes the Traders Guild Caravan spawns while Longen is alive, and Cannibal Infestation nests appear if Tengu is dead. Territory is not static — it is a faction's *current state of power*, and the expedition is how you witness and provoke those shifts.

#callout("Tip:", [The expedition is the world-state engine. Most world-state changes fire from the far corners of the map — killing a UC noble in Bark, a Holy Nation paladin outpost in Okran's Pride, a Southern Hive soldier in the Ashlands — and none of it happens if you stay behind your wall. If you want the map to change under you, the journey *is* the trigger. Plan an expedition whose purpose is a faction's collapse and you will feel the entire region rebalance around it.])
 
Wave 3's mods plug directly into this. Small Caravans is *world-state-gated by design*: its drifters' caravans appear in Stenn Desert while Esata is alive, and in Okran's Pride and Okran's Gulf only after the Phoenix falls — so the same road literally carries different traffic depending on who is still breathing. Accurate Zones Patch reshapes where the faction territories *begin and end* (extending Obedience, connecting Shun to Spider Plains, expanding Dreg), which changes the practical territory a faction's squads actually cover. And the Ashlanders of Behind Enemy Lines - Ashlanders put a new faction on the map in the one corner the vanilla world barely populated — territory that *can* fall into world-state conflict. The expedition's roads are a living system, and every journey is a snapshot of it.

=== Unique Recruits & Legendary Finds

The people of the expedition are its most valuable cargo, and the wiki's Unique Recruits page sets the ground rule: unique recruits "can only ever appear once per game unless imported," have dialogue unique to them, often have higher stats than average recruits, and "a few of them may even be tied to World States." They are finite, irreplaceable resources scattered across the map — which is exactly what makes hunting them an expedition rather than a shopping trip. Wave 3's 42 Unique Recruits extends this principle wholesale: forty-two findable named characters with their own stories, starting with a trail that begins at The Hub and spreading across the whole map, each appearing once per playthrough. It is not a stat mod; it is a *treasure hunt* that repurposes the entire world as its hunting ground.

#callout("Warning:", [A unique recruit who dies is gone for the playthrough. The wiki is explicit that uniques appear once per game (unless you import), and the wave's recruits follow the same rule. Decide before you go whether each named character you find is a keeper — if they are, they get the expedition's best armour, the escort, and the exit route. Treating a unique recruit as expendable is throwing away a one-per-playthrough resource for a moment of convenience.])
 
The legendary finds work the same way. Dwarven Weapons hides unique weapons *in the world with map-hint clues* — not in shops, not in loot tables, but in discoverable locations the hints point you toward — plus a dwarven race and recruits that must be found the same way. Behind Enemy Lines - Ashlanders adds the Ashforge gear set, obtainable only by engaging with its new frontier faction. None of this content is purchasable; all of it is located. That is the wave's entire thesis: the best things in Kenshi are not bought or crafted, they are *found*, and finding them is the journey.

=== Caravans & Trade Routes

The economy of the expedition runs on the roads, and the roads belong to the Traders Guild. The wiki's Traders Guild page lists the caravan spawn zones: Grey Desert, Heng, Stenn Desert, Stormgap Coast, The Great Desert and The Hook. A guild caravan is a Caravan Trader Boss, a Caravan Guard, and a Pack Beast — the exact composition matters because it tells you what a road robbery is worth and what it costs. The Great Desert page is even more specific: a Traders Guild Caravan there is one Boss, seven to eleven Guards and one to three Pack Beasts, aged 100 — a serious escort for a serious cargo, spawning while Longen is alive. These are the map's arteries, and the expedition either uses them or preys on them.

The trader's version of this is knowing what sells where, and the wiki's Hashish page is the classic example of a *commodity with geography*. Hashish is an illegal trade good with a 104% markup, and the Traders Guild will not touch it — but other buyers will: Trader's Edge when the Anti-Slavers control it (1200% markup — the best price on the map), then the Shinobi Towers in the United Cities (600%), then Flats Lagoon. It can be produced via Hashish Production and a Hemp Processor, but those are illegal structures that draw attention. The point is not the drug itself; it is the lesson that *the same item's value is a function of where you sell it and who is in charge there* — exactly the kind of knowledge an expedition accumulates by going places.

#callout("Tip:", [Run the expedition as a caravan when you can, not just an adventure. The Traders Guild's routes (Grey Desert, Heng, Stenn Desert, Stormgap Coast, The Great Desert, The Hook) are the safe roads — patrolled, predictable, and profitable if you buy low at one end and sell high at the other. A squad that travels for story should carry trade goods it can dump at its destination: copper at The Hub's barman, hashish where the markups are, crafted goods from Wave 2's leather economy in the United Cities. The journey pays for itself when the cargo is chosen with the destination in mind.])
 
Small Caravans slots into this economy as the *underside* of the trade routes: drifters' caravans, weaker and poorer than the guild's, easy to rob and selling less, appearing only in certain world states. For the trader it is extra liquidity on the back roads; for the raider it is a soft target worth hitting; for the expedition it is more life on roads that would otherwise be empty. Accurate Zones Patch matters here too — its border fixes mean the caravan zones actually *are* where the map says they are, so the trade routes you plan on the world map hold true when you walk them. Trade is geography, and the wave makes the geography honest.

=== The Cartographer's Endgame

Every expedition is a map being drawn, and the endgame of this wave is the playthrough where the map is the goal: a character — a cartographer, an archaeologist, a chronicler of the deadlands — whose life's work is to see everything the world holds and leave a record of it. This is the role-playing arc this wave is built around, and the mods hand it its tools.

*The surveyor.* Accurate Zones Patch is the mod that makes the map a true record: zones now reach the coasts, Obedience is properly drawn, the Burning Forest sits where it belongs, Dreg is bigger, Shun connects to Spider Plains, the islands are habitable, and the Ashlands keep no safe spaces. A surveyor's purpose is to walk those corrected borders and see the world as it actually is. Biome Edits gives the same surveyor a landscape worth recording — consistent tiling, scattered rocks, a Serpentine Wastes that reads like the Rakes, greener Hoodoo Badlands — because a map drawn of a seam-riddled world is a record of bugs, not of the land.

*The nomad.* Sensible Nomadism's Landmark is the cartographer's instrument: a named, custom map marker you place on locations you decide matter. The Field Research Table means research can happen on the road, the hidden stash means a cache can be buried in hostile territory, and the seven shelters plus Tents' deployable beds mean the surveyor never needs a town. This is a build that *lives* on the land it is mapping — a true expedition faction that treats the outpost as a supply depot and the world as home.

*The discoverer.* The far ends of the map become the endgame. The Ashlands, per the wiki, are "officially un-survivable" in the words of the Tech Hunter Iyo — and behind Enemy Lines puts a living Ashlander culture there to be found, along with the Reed Corsairs of Green Beach and the Ashforge gear. Race | Northern Hive gives the far north its own culture at the Distant Hive Village. 42 Unique Recruits and Dwarven Weapons scatter named people and hidden craft across every region. The cartographer's final entries are the places nobody else bothers to reach.

#callout("Tip:", [Give the cartographer a record that survives them. The game does not let you write in-world — so the record is the player's own: notes on which zones border which, where the acid starts, where the Beak Things nest, which roads the caravans use and which vanish when a leader dies. Run the playthrough as a documentarian and the entire world becomes the content. This is the arc that turns a survival game into a story about seeing it all.])
 
#callout("Warning:", [The endgame is dangerous precisely because it is thorough. The cartographer's route crosses every hazard this chapter has described — acid, gas, sandstorms, Beak Things, world-state-collapse territory — and the mods do not remove any of it: the Ashlands keep no safe spaces, the acid zones still rain, the Beak Things still eat the incapacitated. The difference between a legendary surveyor and a skeleton in the Bonefields is preparation. Travel with the wave's tools — tents, repair kits, fog masks, an escape route — and treat every untouched corner as a boss fight you have not scouted yet.])
