#let callout(title, body) = block(
  fill: rgb("#f2ede0"), inset: 8pt, radius: 4pt,
  stroke: 0.5pt + rgb("#e8590c"),
)[*#title* #body]

== The Krastorio Prodigy: Strategy

The Castaway built a rocket. The Architect built a megabase. The Prodigy has to rebuild *everything*. Krastorio 2 is an overhaul "focusing on end-game technologies and moderately increased complexity" — which understates it: more than 40 new buildings, more than 100 new technologies, three new resources, a research system rebuilt around tech cards, and a combat model where bullets are physical objects. On top of that, this wave enables Space Age and bridges it in with Krastorio 2 Spaced Out, which merges the two overhauls into one longer, more complex playthrough. Nothing you memorised in Waves 0 and 1 transfers as fact — the ratios are different, the science packs are gone, and even the win condition has moved. What transfers is the *method*: read the data, plan the chain, build the scaling systems, and let the tools do the arithmetic. This chapter tells you what Krastorio 2 changes and how the Prodigy survives it. Every structural claim below is sourced from the mods' own portal descriptions and changelogs; specific recipe numbers are deliberately not asserted, because the right way to learn a rebalanced recipe is to look it up in-game (FNEI), not to trust a guide's memory.

=== The New Ores: Imersite, Mineral Water, Rare Metals

Krastorio 2 adds three resources, and its bridge with Space Age keeps them on Nauvis where the base game's engineers already live. They are not decorative — each one is a new branch of the production tree.

*Imersite* is the star. Krastorio 2's page describes it as "a rare end-game resource used in many advanced recipes" — useless on its own, but "when used in advanced manufacturing processes, exhibits ludicrous tensile strength and superconductive abilities." In practice that means imersite is the material the end-game is built from: you mine it, but you do not *use* it until late; the interesting question is always what advanced process consumes it next. Under Krastorio 2 Spaced Out the resource also appears in space, in the form of imersite asteroids in the belt between Aquilo and the inner planets — the *Krastorio 2 Imersite Asteroids* mod in the Modlist chapter adds exactly that, so a late-space engineer can harvest imersite instead of only mining it planetside.

*Mineral water* is "water impregnated with various silts and dusts from the planet's surface" and is used primarily in the production of lithium. Where vanilla has one water source, K2 has two: plain water for boilers and chemical processes, and mineral water for the lithium branch that feeds batteries and beyond. Pump it like water — it behaves like a fluid patch — but treat it as a distinct supply line, because lithium production depends on it and lithium is a common ingredient once the mid-game starts.

*Rare metals* are "an analogous representation of various rare elements (i.e. titanium, platinum, gold)" — a mined metal resource that behaves like iron or copper ore but appears in smaller, more valuable patches and feeds a tier of recipes the common metals cannot. Where iron and copper are your volume, rare metals are your *quality*: they show up in advanced circuits, batteries, armour and late machines.

#callout("Tip:", [YARM from the Wave 0 base tracks any resource patch, and K2's new ores are patches like any other — set a YARM watch on your nearest rare-metals patch the moment you find one, because it depletes like a metal and feeds the whole mid-game. Factory Planner and Rate Calculator see K2's recipes exactly as the game does, so the moment a new ore appears, plan the chain before you build it.])
#callout("Warning:", [Do not let the names fool you into vanilla habits. Mineral water is *not* a substitute for normal water — a base that routes mineral water into its boilers is a base that stalls its power when the lithium line needs every drop. And imersite is explicitly useless on its own: mining it early and stockpiling it is correct, but building a production line around it before the advanced recipes unlock is wasted effort. Mine it, bank it, and let the tech tree tell you when it matters.])

=== New Intermediates & Processing Chains

Every new resource feeds a chain of new intermediates, and K2's overhaul multiplies the number of *steps* between raw materials and finished goods. The lithium produced from mineral water is itself an intermediate; rare metals become specialised products; imersite spawns a family of advanced materials used in end-game machines and buildings. On top of the new resources, K2 adds "more granular fuel trade-offs" and radioactivity, which push the fuel and power chains in directions vanilla never explored.

The Prodigy's discipline in this wave is simple: *never guess a chain.* The base game's recipe set is small enough to memorise; K2's is deliberately not. FNEI (this wave's recipe browser) answers "what makes this?" and "where is this used?" for every item in the game, and it reads the live game data, so it is always right even after a rebalance. The workflow that keeps a K2 base honest is the same one Wave 0 taught, just used more: FNEI to learn what an item needs, Factory Planner to design the block that makes it at the right rate, Rate Calculator to confirm the real machines are hitting the plan, and the bus or rail spine from Wave 1 to move it.

#callout("Tip:", [Bind FNEI to a comfortable key and treat it as part of the HUD. A rebalanced recipe is not a puzzle to solve from memory — it is data to look up. Every time a chain stalls because 'the recipe must have changed', FNEI is the two-second answer.])
#callout("Warning:", [Do not build a production block for an item you have not looked up. K2's recipe rebalances mean an intermediate you remember costing one thing now costs another, and a block built on a stale recipe is a block that silently under-produces forever. Check the recipe when you design it, and re-check it the first time the block runs short.])

=== Research Overhaul: Tech Cards & Research Computers

This is the single biggest conceptual change in the wave. Krastorio 2's page states it plainly: "Instead of science packs, you produce tech cards that are inserted into research computers." The vanilla science-pack ladder — red, green, blue, military, production, utility — is gone. In its place:

*Tech cards* are the new research currency, produced by assembling machines and carried to the lab line like science packs used to be. But they are fed into *research computers*, K2's replacement for the vanilla lab, and there are *three tiers of tech card*, each of which "require their own laboratories." So a K2 research setup is not one lab type fed by six packs — it is (at least) three lab lines, each tied to its own tier of tech card, unlocked and expanded in sequence.

The second half of the overhaul is the *phase-out*. The page notes that "early-game tech cards will be phased out as the game progresses, allowing you to redirect resources to other parts of your factory." A tier-one tech card that powers the early game stops being needed once you can make higher tiers — the early card production line gets dismantled and its machines go back to the factory. This is K2's way of keeping the early research economy lean: progress literally frees up capacity instead of accumulating demand forever.

Under the Krastorio 2 Spaced Out bridge, the tech-card ladder extends into space. K2SO's page describes the higher tiers directly: *advanced tech cards* unlock powerful new buildings on the Space Age planets (an advanced furnace on Vulcanus, laser artillery on Fulgora, an advanced chemical lab on Gleba, and more); *matter tech cards*, made from samples of every resource, enable material transmutation — including of Space Age resources; and *singularity tech cards*, space-exclusive science made of pure matter and asteroid chunks, unlock instant interplanetary travel and the highest tier of logistics. K2SO also adds two new labs, including a space-exclusive singularity lab, and its changelog records that the promethium tech card must be researched in space using singularity labs.

#callout("Tip:", [The phase-out is the research economy's gift — when a tech-card tier becomes obsolete, dismantling its production returns a whole factory's worth of machines. Plan for it from the start: give each early card line a clean footprint you are willing to lose, and do not grief over a card tier you outgrow. That freed capacity is the wave's own refund for progress.])
#callout("Warning:", [Do not build one giant 'science block'. The three tiers each need their own laboratories and their own supply, and the tiers unlock at different times — a single mixed line will either stall the early tiers or starve the late ones. Build per-tier labs from the moment a tier exists, and let the phase-out retire the oldest line rather than the newest. Under K2SO, remember the high tiers are *space* science: singularity tech cards are made in space, in the singularity lab, and the promethium science they gate must also be researched in space.])

=== Adapting the Vanilla Systems

K2 does not add a layer on top of vanilla — it rebalances the base systems themselves, and the Prodigy adapts each one. The general rule: *expect every ratio to differ, and verify before you build.* Specific numbers are deliberately not quoted here, because K2's rebalances are exactly the kind of fact that changes between releases; the tools — FNEI, Factory Planner, Rate Calculator — are the reliable source.

*Smelting.* K2 changes the metal economy around the new resources, rebalances furnace recipes and costs, and adds new buildings and technologies across the smelting line. The iron-and-copper columns you built in earlier waves will not produce at vanilla ratios. Adapt by re-running the plan: treat a furnace column as a black box whose input-to-output number you re-derive with Factory Planner instead of trusting memory.

*Oil and fluids.* K2's recipe rebalances push fluid volumes up, and its "more granular fuel trade-offs" make the fuel economy a real design problem. The pipe network becomes a first-class scaling constraint — which is exactly why the Krastorio team recommends *Fluid Must Flow* (this wave's Mechanics chapter): very large pipes with enormous throughput turn a wall of parallel pipes back into a single, buildable trunk. Adapt by thinking about fluid capacity the way Wave 1 taught you to think about belt capacity, and by treating mineral water as a separate fluid line from ordinary water.

*Power.* K2's feature list includes radioactivity and more granular fuel trade-offs, so the vanilla coal-to-steam ladder is only the start; expect the fuel and power economy to climb through tiers, with new energy sources along the way. Adapt by building power headroom *before* you need it — a rebalanced factory consumes differently than the one in your head, and the P screen plus a small circuit alarm (Wave 1 skills) will catch a power cliff before the inserters stall.

*Trains.* Trains stay the bulk-hauling backbone — and K2 adds new buildings, vehicles and equipment, with "almost all vehicles now have equipment grids." That last change is a quiet QoL upgrade: vehicles become carriers for equipment in a way vanilla limits. Adapt by keeping the Wave 1 rail habits (train limits, chain signals, one-way pairs) — none of them change under K2 — and by treating the new ore patches as normal outposts with normal train schedules, which is exactly what the new resources demand.

*Robots.* The logistic network works as it always did, but K2 brings its own roboports and logistics buildings. The *Krastorio2 - roboport mode colored textures* mod (Graphics chapter) makes the new roboports readable by tinting their rings to their mode. Adapt by keeping the Wave 1 rule — belts for bulk, bots for high-mix — and by learning K2's roboport modes, which the textures exist to make obvious.

#callout("Tip:", [The single most reliable adaptation tool in this wave is the Wave 0 planner stack. Factory Planner does not need to know K2's recipe set by heart — it reads it from the game. Whenever a vanilla habit starts to feel wrong, that is not the mod fighting you; it is the rebalance working as intended. Re-derive the plan and move on.])
#callout("Warning:", [The biggest adaptation failure in an overhaul wave is *assuming*. Assume the old ratio, assume the old recipe, assume the old power curve — and build a block that is quietly wrong. The Prodigy never assumes: every block is planned from current data, and every plan is verified against the real machines with Rate Calculator before it is trusted.])

=== Combat & Biters: Ballistics Against Snappers

Krastorio 2's combat overhaul is not a buff — it is a *physics change*. The page is explicit: "Bullets are now physical objects that have speed, wind resistance, and various AoE effects. Bullets have to travel through space to their target, and can be blocked by solid objects." Two consequences change the whole defence game. First, a shot can *miss* — a projectile has to travel to the target and can be blocked by solid objects in between, so a wall of turrets behind a solid wall can find its own wall in the way. Second, *auto-aim is disabled by default*, requiring the player to choose what to aim at; K2 includes a startup setting to re-enable auto-aim for players who prefer it (or for multiplayer, where the manual model does not play nicely with latency).

On top of the physics, this wave ships *Armoured Biters* (Content chapter), one of the K2 team's recommended companions: a new enemy, the Snappers — "heavily armoured but slower than regular biters." Put the two together and the early defence loop changes shape: the first turrets may not reliably hit, and the armour soaks what does hit. The Prodigy's answer is not bigger guns alone; it is *geometry* — clear fields of fire with nothing solid between muzzle and target — and *volume* — enough turrets that even a low hit rate and soaked damage still converge. K2's own weapons and armour tiers grow with the wave, and the armour/equipment line (higher-tier equipment, equipment grids on almost all vehicles) gives the engineer the survivability the harder enemies demand.

#callout("Tip:", [With projectiles that can be blocked by solid objects, line-of-sight is now a real mechanic: keep a clear lane between your gun turrets and the field they defend, and never stack turrets so the first row blocks the second. Start with the startup setting for auto-aim left *on* if the manual model frustrates you — it exists precisely so the combat overhaul does not become a control fight — and turn it off once you trust your aim.])
#callout("Warning:", [Kiting biters in a circle — the reliable vanilla cheese — stops being reliable when enemies are armoured and projectiles can miss. Armoured Biters is a difficulty-raising companion by design: it exists so the wave's combat asks for actual defence, not just a fast pair of boots. Respect the wall-and-turret economy the same way Wave 0 taught, and expand defence before the pollution cloud grows, because the Snappers are the least of what the end-game sends.])

=== The Endgame: Deep Science and the Win

The Prodigy's victory is not a rocket — it is a *deep science push* through the whole rebuilt tech tree to Krastorio 2's intergalactic transceiver, and under the Space Age bridge the road is longer still. The base game's first launch no longer wins the day; the win condition in this wave is the end of K2's tech tree, reached only after the tech-card economy has climbed all three tiers (and, under K2SO, the advanced, matter and singularity tiers).

Under Krastorio 2 Spaced Out, the endgame changes shape in three concrete ways. First, the *intergalactic transceiver* — K2's win building — is itself reworked: K2SO's changelog records that it must now be made in space and that its recipe was reworked, so the final construction is a space-platform project, not a Nauvis one. Second, *promethium science becomes mandatory for the win condition* and unlocks the ultimate power source — the bridge's changelog confirms the promethium tech card must be researched in space using the singularity lab. Third, the *singularity tech cards* — space-exclusive science made of pure matter and asteroid chunks — gate instant interplanetary travel and the highest tier of logistics, so the very end of the run is about logistics in space as much as it is about science on the ground.

Imersite sits at the heart of this push: the end-game machines and advanced recipes are exactly where the "ludicrous tensile strength" material is consumed, and in K2SO its harvest can extend into the asteroid belt between Aquilo and the inner planets. The *Krastorio 2 Imersite Asteroids* content mod turns that into a real option — imersite as a space resource, gated behind pre-Aquilo technology. The Prodigy's endgame plan is therefore three-legged: keep the tech-card economy fed through every tier, build the space platform and logistics to assemble the transceiver in orbit, and keep a steady imersite supply reaching the advanced machines that turn it into the end-game materials.

#callout("Tip:", [Treat the endgame as a logistics exercise first. The deep-science push consumes enormous quantities of late tech cards, and under K2SO much of the final construction happens in space — so the machine that finishes the run is the logistics network (rail, belts, and the train-dispatch habits Wave 1's Cybersyn chapter taught, scaled up). Nail the imersite supply line early: bank it while it is cheap, because the end-game machines consume it by the belt-load and late-game scarcity is the classic Prodigy stall.])
#callout("Warning:", [Do not let the base game's rocket timing fool you. In this wave the first rocket — or even the first few — are milestones, not the win; the transceiver, promethium science and the singularity research all sit well past it. Budget for a long tail: the deep-science push will outlast everything you built in Waves 0 and 1, and that is the point of the Prodigy's name. Milestones (Graphics chapter) will show you the curve — use it to pace a run that is measured in dozens of hours, not one launch.])

=== The Prodigy's Arc

The three waves were always one story. The Castaway is the castaway — a lone engineer who proves a rocket can be built. The Architect is the builder — the engineer who proves a factory can scale into a megabase of blocks, rail, circuits and robots. *The Krastorio Prodigy* is the master — the engineer who proves they can take a factory where every rule is rewritten and still win. The arc is deliberately about *mastery of change*: nothing from the first two waves transfers as a fact, but everything transfers as a skill. The bus, the rail network, the circuit logic, the robot economy, the module math — all of it still works, all of it still earns its keep, and all of it now has to be *re-verified* against a rebalanced world.

That is the wave's theme, and its mods support it thematically as well as mechanically. *FNEI* is the scholar's tool — the way the Prodigy learns a rebalanced world from its own data. *Milestones* is the historian's ledger — the record of how fast the ladder was climbed, which turns the whole wave into a scored journey with a history worth looking back on. *Armoured Biters* and *Fluid Must Flow* are the K2 team's own nods that the master's world is bigger — harder enemies, more demanding fluids — and *Imersite Asteroids* and the *tech card icons* tie the two anchors together into one coherent space. The RP capstone is simple: by the end of this wave you are no longer the engineer who survived, or the one who scaled — you are the prodigy who *rebuilt*, and who finished a factory that two overhauls conspired to make hard.

#callout("Tip:", [Let the wave's tools tell its story. Start Milestones on day one of the new save and watch the ladder form as the tech cards phase in. Use FNEI the moment the first new recipe confuses you. When the intergalactic transceiver finally assembles in space, open the Milestones history and look back — the wave's whole point is that you can see how far the Prodigy travelled.])
#callout("Warning:", [The Prodigy's failure mode is hubris — assuming the old rules still hold and building at scale before re-verifying. The wave punishes that with stalled chains, starved fluids, and a defence that cannot hit. Stay humble at the beginning of each new system: plan from data, verify with tools, and expand the scaling layers from Wave 1 only once the rebalanced facts are confirmed.])

=== The Krastorio Prodigy's Roadmap

The whole wave, one glance.

1. *Start the K2SO save.* Space Age enabled, Krastorio 2 + Krastorio 2 Spaced Out at the top, the Wave 0 QoL base carried in. Start Milestones on day one. This is *The Setup*.
2. *Learn the new ground rules.* Read FNEI for the first rebalanced recipes; note the mineral water, rare metals and imersite patches. This is *The New Ores*.
3. *Build the first tech-card economy.* Research computers, tier-one labs, the first tech cards — and plan the line so the phase-out can retire it cleanly. This is *Research Overhaul*.
4. *Re-derive the vanilla systems.* Rebuild smelting, fluids, power and the fuel economy against current data; bring in Fluid Must Flow for the pipe trunk. This is *Adapting the Vanilla Systems*.
5. *Make the factory scale again.* Rebuild the bus and rail spine from Wave 1 around the new resources; YARM watches the new ore patches, and the train-dispatch and circuit skills Wave 1 taught do the scaling work. This is *Scaling the Rebalanced Factory*.
6. *Respect the new combat.* Clear fields of fire, volume of turrets, Armoured Biters respected, auto-aim set to taste. This is *Combat & Biters*.
7. *Climb the card tiers.* Tier two, then tier three; dismantle each retired card line as the phase-out dictates. This is *The Tech-Card Ladder*.
8. *Go to space.* Advanced, matter and singularity tech cards; imersite asteroids in the belt; the singularity lab in orbit. This is *The K2SO Bridge*.
9. *Assemble the win.* Build the intergalactic transceiver in space, research the promethium science, unlock the ultimate power source, and push the deep science to its end. This is *The Endgame*.
10. *Look back.* Open Milestones, review the ladder, and close the Prodigy's arc. This is *The Capstone*.

Each step leaves the factory working while you build the next — and every step is a re-verification, a chance to prove the old skills still hold in a world where every rule changed. The Prodigy's reward is the one thing the first two waves could not give: the knowledge that it was done *twice* — once by the numbers, and once with the whole book rewritten.
