#import "../../lib.typ": tip, concept, warning

= How to Play Starbound

This chapter is a focused walkthrough for new players. It covers everything you need to get from the intro mission through the main story. It is not a comprehensive wiki — for detailed item stats and mechanics, the #link("https://starbounder.org")[official Starbound Wiki] is your companion.

== Controls and Interface

=== Basic Controls

| Key | Action |
|-----|--------|
| A / D | Move left / right |
| Space | Jump |
| S | Crouch / drop through platforms |
| Left click | Use Matter Manipulator / attack |
| Right click | Secondary ability (weapon-dependent) |
| R | Switch Matter Manipulator mode |
| E | Interact (open doors, talk, loot) |
| I | Open inventory |
| C | Open crafting menu |
| J | Open quest journal |
| Tab | Toggle hotbar |
| 1-6 | Hotbar slots |
| Esc | Pause / main menu |

#tip[
  Press R to quickly cycle between Matter Manipulator modes: mine, paint, wire, and scan. You will use mining mode 90% of the time.
]

=== The HUD

- *Top-left:* Health bar (red) and Energy bar (green). Energy recharges automatically. Health requires bandages, salves, or beds.
- *Top-center:* Hotbar — your 6 active items. Left and right slots are for two-handed dual-wielding.
- *Top-right:* Current planet name, weather indicators, and status effects.
- *Bottom-left:* Chat and system messages.

== Your First Hour

=== The Intro Mission

You start aboard a Protectorate ship. Follow the on-screen prompts — they teach you the basics of movement and interaction. The intro mission is linear and unskippable on a first playthrough.

Key moments:
- *Matter Manipulator:* You receive it from the locker. This is your most important tool.
- *Combat tutorial:* You will fight basic enemies with a sword. Left click to swing.
- *The emergency:* Something goes wrong. Follow the prompts. You cannot die during the intro.
- *Escape:* You will board a shuttle. This is a cutscene. Watch it — it sets up the entire story.

=== Your First Planet

After the intro, you crash-land on a procedurally generated *Lush* planet. This is your first real taste of Starbound.

#concept[
  *Procedural generation:* Every planet in Starbound is generated by an algorithm. Two players on a "Lush" planet will see different landscapes, different dungeons, and different NPCs. Your journey is uniquely yours.
]

*What to do first:*

1. Follow the initial quest prompts from SAIL (your ship's AI)
2. Gather basic resources: *Wood* from trees, *Cobblestone* from the ground
3. Craft a *Crafting Table* from your ship's basic crafting menu (press C)
4. Craft *Wooden Platforms* — you will need them for climbing
5. Explore the surface. Look for chests, NPC camps, and cave entrances

#tip[
  Hold Shift to place blocks in a 1x1 grid instead of the default 2x2 mining mode. This is essential for precise building and bridging across gaps.
]

=== Your First Cave

Caves are where you find *Core Fragments* — a critical early-game resource needed to power your ship and activate the FTL drive.

1. Craft *Torches* from Wood and Coal
2. Find a cave entrance (dark hole in the ground) or dig down
3. Place torches as you go — enemies spawn in darkness
4. Look for glowing red ore: *Core Fragments*
5. You need 20 Core Fragments to activate the FTL drive

#warning[
  Caves get dangerous at night and at deeper levels. Craft a basic weapon and some *Salves* (from Plant Fibre) before venturing too deep. If you die, you drop items — but you can recover them by returning to the spot.
]

=== Activating the FTL Drive

Return to your ship with 20 Core Fragments. Interact with the FTL drive console (center of the ship) to activate it. This unlocks interstellar travel — congratulations, you are no longer stranded.

== Core Survival Systems

=== Hunger

You have a hunger meter (visible in the inventory screen, top-left). It drains slowly over time. Eating food restores it.

- *Cooked food* restores more hunger than raw ingredients
- Craft a *Campfire* (10 Wood + 1 Torch) to cook meat and produce
- Plant *crops* on your ship or a planet base for a renewable food supply
- If your hunger bar empties, you start taking damage

#concept[
  Different foods provide different buffs — increased health, energy regen, speed, and more. Experiment with cooking recipes. A well-fed explorer is a surviving explorer.
]

=== Temperature

On some planets, temperature is lethal:

- *Cold planets:* You will see a freezing status effect. Craft *Campfires* or *Torches* and stand near them to warm up.
- *Hot/Radioactive planets:* You take damage without protection. Craft *Breathing EPP* upgrades at an Anvil.
- *Planets without atmosphere:* You take suffocation damage. Wear a *Breathing EPP*.

=== Death and Recovery

When you die, you drop a portion of your *Pixels* (currency) and some items at your death location. You respawn on your ship.

- *On Normal difficulty:* You drop 30% of your pixels and some items. You can recover them.
- *On Survival difficulty:* You drop items and must eat to survive. Food is scarce.
- *On Hardcore difficulty:* Permanent death. Your character is deleted.

#tip[
  For your first playthrough, choose *Normal* difficulty. Survival and Hardcore add significant challenge that is more enjoyable once you understand the game's systems.
]

== Tech and Progression

=== Story Missions

The main story is accessed through SAIL on your ship. Missions are planetary instances — you beam down to a special dungeon and cannot leave until you complete or fail the objective.

Mission order (approximate):

1. *Erchius Mining Facility* — Unlocks FTL travel to other systems
2. *Scan floran artifacts* — Unlocks the Floran artifact mission
3. *Ceremonial Hunting Caverns* (Floran) — First boss: Ixodoom
4. *Scan hylotl artifacts* — Unlocks Hylotl artifact mission
5. *Grand Pagoda Library* (Hylotl) — Boss: Asra Nox appears
6. *Scan avian artifacts* — Unlocks Avian artifact mission
7. *Great Sovereign Temple* (Avian) — Boss: Kluex Avatar
8. *Scan apex artifacts* — Unlocks Apex artifact mission
9. *Miniknog Stronghold* (Apex) — Boss: Big Ape
10. *Scan glitch artifacts* — Unlocks Glitch artifact mission
11. *Baron's Keep* (Glitch) — Boss: Bone Dragon
12. *The Ruin* — Final boss: The Ruin (Heart of the Ruin)

#tip[
  Between missions, explore new planet types, upgrade your gear, and recruit crew members. The story is not a race — it is the backdrop for your exploration.
]

=== Matter Manipulator Upgrades

Your Matter Manipulator improves as you progress:

- *Base:* 2x2 mining area, slow speed
- *Upgrade 1:* 3x3 mining area (requires Manipulator Modules)
- *Upgrade 2:* 4x4 mining area, faster speed
- *Upgrade 3:* 5x5 mining area, liquid collection

Find *Manipulator Modules* in chests, as quest rewards, and from merchants.

=== Techs

Techs are abilities you equip at a *Tech Console* on your ship. You unlock slots by completing story missions.

Key tech types:
- *Movement:* Dash, Sprint, Pulse Jump, Air Dash
- *Body:* Distortion Sphere (roll through small gaps), Spike Sphere (climb walls)
- *Head:* Light (illuminates area), Oxygen (underwater breathing)

#concept[
  Techs are game-changers. Dash + Pulse Jump makes exploration dramatically faster. Prioritize unlocking these two as early as possible.
]

== Crafting and Gear Progression

=== Crafting Stations

| Station | Requires | Produces |
|---------|----------|----------|
| Basic Crafting (C key) | Nothing | Torches, platforms, campfire |
| Inventor's Table | Crafting Table | Basic tools, weapons, armor |
| Spinning Wheel | Inventor's Table | Fabric, bandages |
| Anvil | Inventor's Table | Metal armor, weapons, EPPs |
| Forge | Anvil | Advanced metal gear |
| Replicator | Forge | Endgame gear |
| Separator's Table | Replicator | Perfect-tier gear |

=== Ore Tiers

| Tier | Ore | Found On | Armor Set |
|------|-----|----------|-----------|
| 1 | Iron | Lush, Forest | Iron Armor |
| 2 | Tungsten | Desert, Savannah | Tungsten Armor |
| 3 | Titanium | Ocean, Jungle | Titanium Armor |
| 4 | Durasteel | Toxic, Mutated | Durasteel Armor |
| 5 | Aegisalt / Ferozium / Violium | Frozen, Fiery, Radioactive | Racial Armor |
| 6 | Solarium | Fiery, Volcanic | Solarium Armor |

#tip[
  Always upgrade your armor before tackling a new tier of planets. The damage reduction difference between tiers is substantial. A Tungsten set on a Tier 4 planet will get you killed in seconds.
]

=== EPPs (Environmental Protection Packs)

EPPs are back-slot equipment that protect against planetary hazards:

- *Breathing EPP:* Survive on airless planets and moons
- *Radiation EPP:* Survive on radioactive planets
- *Heating EPP:* Survive on frozen planets
- *Cooling EPP:* Survive on fiery planets

Craft EPP upgrades at an Anvil or Forge. Higher-tier EPPs combine multiple protections.

== Crew and Colony

=== Recruiting Crew

NPCs in settlements sometimes offer to join your crew after you complete a quest for them. Crew members provide:

- *Engineers:* Increase ship fuel efficiency
- *Soldiers:* Follow and fight with you on planets
- *Medics:* Regenerate your health
- *Mechanics:* Increase ship speed
- *Janitors:* Slightly improve various ship functions
- *Tailors:* Change your crew's uniform colors

#concept[
  A full crew of 12 members provides significant passive bonuses. Recruit actively — every NPC you help might join you, and the ship feels alive with a full complement.
]

=== Colony Building

Deploy a *Colony Deed* on a planet to establish a colony. Place furnished rooms with appropriate items to attract specific tenant types. Tenants pay rent (pixels or items) and may offer quests.

Colony requirements:
- Enclosed room with background walls
- Door
- Light source
- At least one piece of furniture

Attract specific tenants by placing themed furniture. A *Cooking Table* attracts a chef. A *Weapon Rack* attracts a guard.

== Farming

Craft a *Wooden Hoe* to till soil. Plant seeds (found while exploring). Water crops by building near a water source or using a *Sprinkler* (crafted later).

- *Staple crops:* Wheat, Rice, Potato — reliable hunger fillers
- *Cash crops:* Boneboo, Neonmelon — sell for high pixel value
- *Utility crops:* Cotton — makes fabric for bandages and armor

#tip[
  Build a farm on your ship. The ship is always loaded while you are on it, so crops grow passively as you travel. A medium ship farm can make hunger management trivial.
]

== Mechs

Unlocked after completing the *Dr. Akaggy's* introductory quest (triggers after a few story missions). Mechs are large exosuits for space and planet exploration.

- Mechs can operate on *space encounters* (anomalies, asteroids, enemy ships)
- Upgrade mech parts at a *Mech Assembly Station*
- Mechs use Energy instead of Health
- Mechs cannot be used inside story mission instances

== Bounty Hunting

After the main story, visit any *Peacekeeper Station* to begin bounty hunting. Bounties are procedurally generated missions with unique targets and rewards. A good post-game activity that sends you to planets you might not otherwise visit.
