// Enhanced Liberty — Main Document
// Include template, render cover, compose all chapters

#import "template.typ": cover, sys-impact, liberty-body-text, liberty-gold, liberty-heading, liberty-link

// Render cover page
#cover(
  title: "Enhanced Liberty",
  subtitle: "GTA IV Modlist — v1.0.8.0",
  logo_path: "../assets/logo.jpg",
  waves: "Wave 0: Fresh Off the Boat  /  Wave 1: City of Dreams",
)

// Table of Contents page
#page[
  #set heading(numbering: none)
  #set text(font: ("Fira Sans", "Roboto"), size: 14pt, weight: "bold", fill: liberty-heading)
  Table of Contents
  #block(height: 0.5cm)
  #outline(
    indent: auto,
    depth: 2,
  )
]

// Reset numbering for content pages
#set page(numbering: "1")

// Include all chapters (generated by convert.js from guide/*.md)
#include "chapters/01-installation.typ"
#include "chapters/02-wave-0-mods.typ"
#include "chapters/03-wave-0-guide.typ"
#include "chapters/04-wave-1-mods.typ"
#include "chapters/05-wave-1-guide.typ"
#include "chapters/06-fusionfix-config.typ"
