#!/usr/bin/env node
// Build PDF from markdown chapters using Pandoc → Typst pipeline
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { execSync } from 'child_process';

const CHAPTERS = [
  { file: 'modlist/chapter-01-what-is-rimworld.md',    title: 'Chapter 1' },
  { file: 'modlist/chapter-02-setup.md',                title: 'Chapter 2' },
  { file: 'modlist/chapter-03-framework.md',            title: 'Chapter 3' },
  { file: 'modlist/chapter-04-bugfixes-performance.md',  title: 'Chapter 4' },
  { file: 'modlist/chapter-05-ui-hud.md',               title: 'Chapter 5' },
  { file: 'modlist/chapter-06-graphics.md',             title: 'Chapter 6' },
  { file: 'modlist/chapter-07-audio-music.md',          title: 'Chapter 7' },
  { file: 'modlist/chapter-08-gameplay-enhancements.md', title: 'Chapter 8' },
  { file: 'modlist/chapter-09-weapons-combat.md',       title: 'Chapter 9' },
  { file: 'modlist/chapter-10-world-variety.md',        title: 'Chapter 10' },
  { file: 'modlist/chapter-11-monsters-creatures.md',   title: 'Chapter 11' },
  { file: 'modlist/chapter-12-npc-interactions.md',     title: 'Chapter 12' },
  { file: 'modlist/chapter-13-alien-breeding.md',       title: 'Chapter 13' },
  { file: 'modlist/chapter-14-gameplay-guide.md',       title: 'Chapter 14' },
  { file: 'modlist/chapter-15-troubleshooting.md',      title: 'Chapter 15' },
  { file: 'modlist/appendix-modlist-reference.md',      title: 'Appendix A' },
  { file: 'modlist/appendix-resources.md',              title: 'Appendix B' },
];

const VERSION_FILE = 'version.json';
const OUTPUT_TYP   = 'modlist.typ';
const OUTPUT_DIR   = 'output';

const v = JSON.parse(readFileSync(VERSION_FILE, 'utf-8'));
const guideVersion = v.version;
const gameVersion  = v.gameVersion;
const pubDate      = v.date;

const out = [];

// ── helpers ──

function write(...args) { out.push(args.join('\n')); }

function pandoc(file) {
  const cmd = `pandoc -t typst "${file}"`;
  const raw = execSync(cmd, { encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024 });
  let lines = raw.split('\n');
  // Strip Pandoc heading labels (<...>) — they cause duplicate-label errors
  lines = lines.filter(l => !/^<[a-z0-9][-a-z0-9]*>$/.test(l.trim()));
  // Strip empty heading-label lines (blank after stripped label)
  const outLines = [];
  for (let i = 0; i < lines.length; i++) {
    const prevBlank = i > 0 && lines[i-1].trim() === '';
    const currBlank = lines[i].trim() === '';
    if (prevBlank && currBlank) continue;
    outLines.push(lines[i]);
  }
  return outLines.join('\n');
}

// Remove Pandoc's #figure(align(center)[...], kind: table) wrapper
// and inject styled-table in place of #table
function postProcessTable(text) {
  const result = [];
  let i = 0;
  while (i < text.length) {
    // Look for #figure( align(center)[ pattern
    const figStart = text.indexOf('#figure(', i);
    if (figStart === -1) { result.push(text.slice(i)); break; }

    // Check it's actually the figure(align(center)[#table pattern
    const afterFig = text.slice(figStart + 8).trimStart();
    if (!afterFig.startsWith('align(center)[')) {
      result.push(text.slice(i, figStart + 1));
      i = figStart + 1;
      continue;
    }

    // Push content before the figure wrapper
    result.push(text.slice(i, figStart));

    // Find the content start inside align(center)[...]
    const afterFigRaw = text.slice(figStart + 8);
    const bracketOffset = afterFigRaw.indexOf('align(center)[') + 'align(center)['.length - 1;
    const contentStart = figStart + 8 + bracketOffset;

    // Match the ] that closes align(center)[...]
    let depth = 1;
    let j = contentStart + 1;
    while (j < text.length && depth > 0) {
      if (text[j] === '[') depth++;
      else if (text[j] === ']') depth--;
      j++;
    }

    // After the ], expect whitespace, then , kind: table )
    const remainder = text.slice(j);
    const figEndMatch = remainder.match(/^\s*,\s*kind:\s*table\s*\)/);

    if (figEndMatch) {
      // Extract inner table content and replace #table( with #styled-table(
      let inner = text.slice(contentStart + 1, j - 1); // between [ and ]
      inner = inner.replace(/#table\(/g, '#styled-table(');
      result.push(inner);
      i = j + figEndMatch[0].length;
    } else {
      // Not a table figure, push original
      result.push(text.slice(figStart, figStart + 1));
      i = figStart + 1;
    }
  }
  return result.join('');
}

// ── styles ──

write('// Generated by build-pdf.mjs — do not edit manually');
write('');
write(`#set page(margin: (left: 2.5cm, right: 2.5cm, top: 2cm, bottom: 2cm))`);
write(`#set text(size: 11pt)`);
write(`#set heading(numbering: "1.1")`);
write(``);
write(`// Link colour — warm gold, not blue`);
write(`#show link: set text(fill: rgb("#C8A84E"))`);
write(``);
write(`// Table wrapper with horizontal stripes`);
write(`#let styled-table(..args) = {`);
write(`  table(`);
write(`    fill: (r, c) => if calc.odd(r) { luma(240) } else { white },`);
write(`    stroke: 0.5pt + luma(200),`);
write(`    inset: 6pt,`);
write(`    ..args,`);
write(`  )`);
write(`}`);
write(``);

// ── cover page ──

write(`#page(fill: rgb("#1a1a2e"), margin: (left: 3cm, right: 3cm, top: 2cm, bottom: 2cm))[`);
write(`  #align(center + top, text(size: 12pt, fill: luma(150), weight: "bold")[A Beginner-Friendly Modding Guide])`);
write(`  #v(3cm)`);
write(`  #align(center, text(size: 48pt, weight: "bold", fill: white, tracking: 2pt)[Home Among the Stars])`);
write(`  #v(0.5cm)`);
write(`  #align(center, text(size: 20pt, fill: rgb("#D4A017"), weight: "semibold")[RimWorld Modlist \\& Learning Guide])`);
write(`  #v(0.5cm)`);
write(`  #align(center, text(size: 13pt, fill: luma(160), style: "italic")[Targeting RimWorld ${gameVersion} + All DLC])`);
write(`  #v(4cm)`);
write(`  #align(center, text(size: 14pt, fill: luma(200))[Version ${guideVersion}])`);
write(`  #align(center, text(size: 12pt, fill: luma(150))[${pubDate}])`);
write(`]`);
write(``);

// ── table of contents ──

write(`#pagebreak()`);
write(`#outline(title: [Contents], indent: auto, depth: 1)`);
write(``);

// ── chapters ──

for (const ch of CHAPTERS) {
  write(`#pagebreak()`);
  write(postProcessTable(pandoc(ch.file).trim()));
  write(``);
}

// ── write .typ file & compile ──

writeFileSync(OUTPUT_TYP, out.join('\n'), 'utf-8');
console.log(`Written ${OUTPUT_TYP}`);
console.log('Compiling…');

if (!existsSync(OUTPUT_DIR)) mkdirSync(OUTPUT_DIR, { recursive: true });

const pdfName = `Home-Among-the-Stars-v${guideVersion}.pdf`;
const pdfPath = `${OUTPUT_DIR}/${pdfName}`;

try {
  execSync(`typst compile "${OUTPUT_TYP}" "${pdfPath}"`, { stdio: 'inherit', cwd: process.cwd() });
  console.log(`\n✓ PDF generated: ${pdfPath}`);
} catch (e) {
  console.error(`\n✗ Compilation failed. Check ${OUTPUT_TYP} for errors.`);
  process.exit(1);
}
