#let callout(title, body) = block(
  fill: rgb("#f7e8d8"), inset: 8pt, radius: 4pt,
  stroke: 0.5pt + rgb("#d97b3a"),
)[*#title* #body]

== The Conqueror: Strategy

Wave 3 ended with a map you could cross. Wave 4 is what the map is *for*: taking it. This is the warfare chapter — how the factions of Kenshi view you and each other, how the raids on your walls actually work, how an army is built and commanded, how a world state is turned into a conquest, what the endgame enemies are made of, and how a playthrough that has conquered everything is *supposed* to end. The mods in this wave exist to make the conquest deeper and the world more reactive to it — never to hand you the victory on a plate.

The core idea to internalise is that in Kenshi, *power is territorial, and territory is a statement other factions read*. The moment your outpost grows, tax men, tribute rounds and prayer days start arriving; the moment you kill a faction's leader, that faction's patrols thin and its bases change hands; the moment you stand in the way of a great power, that power decides you are a problem. Wave 4 is about learning to play that system instead of just surviving inside it — and the mods below make the system respond harder, in both directions.

#callout("Warning:", [Conquest is not a reward the world applauds — it is a provocation the world answers. In Kenshi the difficulty curve does not flatten when you win; it sharpens. Killing leaders makes the survivors angrier, taking territory puts you in range of stronger neighbours, and a conquered faction's remnants keep coming from hidden places. The mods in this wave are chosen to respect that: everything that makes the world react makes it react *harder*, not softer. If you want a playthrough where winning is easy, this is the wrong wave.])
 
=== Faction Relations & Diplomacy

Kenshi's world runs on a relation score that every faction holds toward you, and the wiki's Factions page sets the ground rules: there are 93 factions in the game, "some factions will be hostile to any person they see by default, such as: Cannibals, Berserkers and Swamp Ninjas," and you can gain perks and bonuses by getting into a faction's good graces. Relations are not a single number; they are a web. Joining the Anti-Slavers, for example, is a -30 to the Traders Guild, which otherwise sits at +100 with the Slave Traders and the United Cities. The choice to side with one power is simultaneously the choice to offend another — the whole map is watching the same ledger you are.

The concrete levers are world-state actions, not dialogue trees. The wiki's Traders Guild page is explicit: kill or imprison Lady Kana or Longen and you "seriously damage this faction's view towards you"; choose pro-slavery dialogue with them and relations rise, anti-slavery and they fall. Killing or kidnapping a faction's leader is the blunt instrument of diplomacy — it rebalances every faction that cared about them. The precise instrument is reading *who* cares. The United Cities' caravan trade hinges on Longen; the Holy Nation's patrols hinge on which of its leaders are dead and which are alive; the Shek Kingdom's tribute events only fire while its leaders live. Diplomacy in Kenshi is a map of dependencies, and the conqueror's skill is knowing which leader's death rebalances which part of the world.

#callout("Tip:", [Allies fight with you — and they can be earned through deeds, not just bought. Minor Faction Overhaul - Sand Ninjas makes the Sand Ninjas allyable by rescuing one of their strongest Jounins from the United Cities; once allied, they "will protect your squad if they pass them in the desert, as well as assisting in Slaver and Hero League raids." That is diplomacy as a quest chain: a rescue that converts a neutral desert faction into a mobile escort. When planning a war, count your allies the way you count your fighters — a faction that patrols your road is a faction that holds your supply line.])
 
Relations have a ceiling below warfare, and the system is deliberately hostile to total harmony. Some factions are simply hostile by default (Cannibals, Berserkers, Swamp Ninjas) and no amount of goodwill changes that; the wiki is explicit that they will attack any person they see. Faction uniforms add a disguise layer — wearing a faction's uniform makes you "in Disguise" and can get you arrested for Uniform Theft, and it only becomes a safe fashion choice when you are actually allied. The strategic lesson is not to treat relations as a bar to max out, but as a *portfolio*: keep the factions you trade with warm, keep the factions you raid cold, and never expect the default-hostile ones to negotiate.

=== Raids, Sieges & Defense

Raids are the other half of the faction system — the territorial pressure that answers your existence. The wiki's Raid page defines the shape: a raid is a territorial event, and a faction like the Band of Bones assaults with "2-4 squads of 4-7" raiders; raids trigger when your base sits within roughly 5,000 meters of a hostile faction's camp; raiders "break down gates and attack characters," and they give a speech before attacking. A raid is not random — it is a faction deciding, on a schedule, that you owe it your attention. Defense in Wave 4 is about turning that scheduled attention into something your walls and turrets profit from.

The visitor system is the peacetime version of the same pressure. The wiki's Guide to Building an Outpost lists the factions that visit outposts with demands: the Hounds come for extortion, the Shek Kingdom sends a Tribute Round, the Holy Nation holds a Prayer Day, and the United Cities send a tax man. Each visit is a choice dressed as an event — comply, refuse and face the consequences. The wiki is blunt about refusal: "they might be immediately attacked, or the squad will retreat with the promise of returning with an army." The Tribute Round page is even more specific about the conditions: it triggers within 1,500 meters of a Shek Kingdom settlement, only while Bugmaster, the Phoenix, Bayan, Seto and Esata are all alive and you are neither ally nor enemy, with a 15% daily chance inside 1,000 meters. These visits are the faction ledger made flesh: they are how the map's powers collect what they think you owe them.

#callout("Warning:", [A base that grows is a base that gets raided harder — and refusing a demand escalates the schedule. The Raid page's numbers (Band of Bones at 2-4 squads of 4-7) are the *start*; raid size tracks your settlement's reputation and your distance from hostile camps, so the bigger you build and the closer you settle to a hostile faction's doorstep, the heavier the waves. Plan defense in tiers: walls that hold a gate, turrets that cover the approach, and a kill-zone that funnels attackers into overlapping fire. Wave 2's Vanilla Crossbow Turrets and Portable Crossbow Turret kit are the weapons side of this equation — Wave 4 is about the doctrine that uses them.])
 
The mods in this wave feed directly into the siege picture. Reactive World adds post-collapse siege content of its own: after you take out the Holy Nation's leaders, "you will be met with regular raids from the remnants of the HN, who have gathered around some new leaders of their own in hidden locations. There are bread crumbs out in the world to help you track down these new leaders, and until you do the raids" keep coming. A defeated faction does not vanish in Wave 4 — it becomes a guerrilla army with named, findable leadership. That changes the siege doctrine: wiping a faction is no longer a single battle, it is a hunt for hidden commanders, and the raids keep coming until the hunt is complete. This is the wave's core argument — that victory over a faction should be *earned twice*.

=== Army Management

The army is the tool of conquest, and Kenshi caps how many characters you can field: the vanilla squad cap sits at 30, and any mod that simply raised it was cut in earlier waves because it handed out force without a cost. Wave 4's answer to army-building is different — it grows the army through the *costly*, *earned* path of recruiting prisoners, not by raising the cap. The distinction matters: a bigger army is a power spike if it is free; a bigger army is a strategy if every member is paid for, captured, or rescued.

Recruit Prisoners for Cats is the wave's army-management core, and its whole design is a response to the power-spike problem. It is the balanced rebuild of the classic Recruit Prisoners mod, and its description is explicit about why: "With the original mod it was too easy to acquire an army of really strong npcs (which took the challenge and difficulty away), so I added costs to recruit them. A single Ninja or high level can really change your game, so it shouldn't be easy to recruit them." The mechanic is capture-and-pay: knock an NPC out, cage them, speak to them, and pay cats to buy their loyalty. The cost gate is the point — it converts the game's endless appetite for cats into a real decision about who joins and when.

#callout("Tip:", [The army the wave wants you to build is a *mixed* force, not a flood. Prisoner recruitment gives you specialists — a captured Ninja or a high-level warrior — at a real price, which means each one is a choice about role, not just a body. Pair them with the generic recruits of Wave 0 (sword-for-hire at roughly 3,000 cats base) for the rank and file, keep your unique recruits from Wave 3 as the irreplaceable core, and let the Sand Ninjas of Minor Faction Overhaul - Sand Ninjas be the faction that escorts your columns through the desert for free. An army of thirty identical swords is weaker than twenty fighters with defined jobs and a cavalry faction watching your flank.])
 
Army management also means the logistics around the fighters. Every soldier eats, sleeps, heals and needs gear — and the earlier waves already built that supply chain: Wave 1's food and farming, Wave 2's crafting and turrets, Wave 3's camping and repair economy. The conqueror's army is the first wave's farms + the second wave's forge + the third wave's logistics + this wave's recruitment. The tactical detail the wiki supports: cut damage never heals by itself and needs First Aid Kits, while blunt damage regenerates — so a garrison that fights bludgeoning weapons (Shek, cannibals) recovers without bandaging, while a garrison that fights cutting weapons (ninjas, sabre squads) burns through kits. Staff your medics accordingly before the siege starts, not after.

=== World Conquest

World conquest in Kenshi is not a flag you plant; it is a sequence of world-state changes you provoke. The wiki's World States page lays out the mechanism precisely: "killing or kidnapping of the important leader(s) of factions" reduces that faction's squad spawn rates, and "the faction base is then destroyed or occupied by a different faction." The conditions are strict — imprisoning a leader counts as killing for most purposes, but an "alive" condition means alive *and free*, so a captured-but-breathing leader still triggers death states. Conquest is, at the mechanical level, a ledger of leader deaths and the territories those deaths re-assign.

The waves of that ledger are the actual campaign. Kill the leaders of a small faction and its patrols thin to nearly nothing; kill a great power's leaders and the entire region rebalances — patrols override, settlements change hands, remnant factions form. Wave 3 already documented the Holy Nation example: with the Phoenix, Valtena and Seta all dead, its patrols are overridden by the Holy Army Bandits and the Diaspora of Strayed Paladins. Wave 4's mods deepen the ledger. Reactive World is the conquest amplifier: it fills out the world's reaction systems with effects the vanilla game left empty — the Hub rebuilding under the Shek Kingdom or Holy Nation if their forces take territory, the Western Hive "going crazy if their Queen is kidnapped" and pushing to rescue her with no mercy for anyone in their way, and cannibal factions being separated and given their own dynamics.

#callout("Warning:", [Conquest has a cost in *how you are seen*, and some victories are pyrrhic. Taking out a faction's leaders triggers the world-state conditions that spawn the remnants — Reactive World's hidden Holy Nation commanders, the UC's Cannibal Infestation nests that appear when Tengu dies, the patrol overrides that put new hostiles on old roads. The map you conquer is not empty afterwards; it is *re-occupied*, often by factions angrier than the ones you removed. Budget for the occupation, not just the conquest: the war is won in the campaign, but the peace is held by garrisons, and the garrisons are supplied by the army-management loop above.])
 
Take Over the World and its sibling Vassalize Over the World — both of which let you personally claim towns — were deliberately *not* included, and the reason is the wave's own honesty rule. Take Over the World's description warns that "Reactive World and other large mods will conflict and break the system," so the two cannot both run. Between a mod that hands you every town after killing its leaders (and leaves them empty — "There will be no people in the town after you take it over, so all shops and so on are lost") and a mod that makes the world react believably to the conquests you earn, this wave chose the one that keeps the challenge honest. The towns you want are taken by the world-state system, not handed over by a mechanic.

=== Endgame Enemies

The endgame of a conqueror is defined by what it fights, and Kenshi's late-game enemies are where the difficulty sharpens to its point. The far north holds the Cannibals — a faction the wiki describes as hostile to everyone, with a default -100 relation toward the world, living in the Cannibal Plains and Darkfinger but migrating as far as the Great Desert, Bast, Okran's Valley and Dreg, and "attack other factions and carry unconscious organic members of other factions to their camp or Village." The Shrieking Forest holds the Shrieking Bandits, and the far southeast holds the Ashlands — poison gas, the Skeleton Legion, and the Second Empire's leftovers. These are the walls of the map, and the endgame is measured against them.

Wave 4's mods make those walls taller rather than shorter. Cannibals Expanded adds new cannibal units (the Mancatchers, Tenderizers and Punishers), upgrades the high-ranking leaders (the Grand Wizard, the Meat Lord, even Canhead) with new armour and weapons, and adds new weapons with rare quality grades to find — and its description warns plainly that "this will make the cannibals a more formidable force." Shrieking Bandits Expanded does the same for the Shrieking Forest, adding themed squads (the Babblers, the Howlers, the Moaning Samurai, the Screeching Beasts and the mysterious footmen) and warning that "this will make the Shrieking forest a more dangerous location." Thrashers adds a new enemy type outright: "mobile ranged platforms capable of doling out a wall of razor-sharp harpoons" — slow and weak up close, but able to "waste your squad from 500 meters away before you even see it."

#callout("Tip:", [Endgame enemies reward doctrine, not just stats. Thrashers is the purest example: the mod's own description says you must "close the distance as quickly as possible" because a thrasher is unmatched at range and near-defenceless in melee. That is a target profile, not a stat wall — fast close-range squads with heavy cut damage and strong Toughness beat it, while a ranged-vs-ranged duel loses. Cannibals Expanded's new units and leader upgrades are the same lesson in a different form: the new armours and weapons change what you need to bring (armour penetration, cut defence) and which leaders are worth assassinating first. Read the mod's content list like an intelligence briefing, and plan the counter before you march.])
 
The three endgame mods also share the same honest framing: they add threat, they do not add reward-padding. None of them hands you stronger gear for free — the new weapons are "for you to find," earned from the new units. That keeps them on the right side of the wave's rule: the challenge gets deeper, and the payoff is tied to defeating the challenge. This is what separates a curated warfare list from a cheat list — the difficulty is the product.

=== The End: Conquering the Playthrough

Every conqueror's story has a final chapter, and Kenshi gives you a genuine one: the playthrough where you have killed the leaders, toppled the powers, and the world has settled into the shape you made. The wiki's World States page defines the endgame condition precisely — the faction base is destroyed or occupied by a different faction, patrols thin to remnants, the map's powers are replaced. Wave 4's mods exist so that the ending is a *story*, not a cleanup chore.

#callout("Tip:", [The end is a prompt, not a stop. Once the great powers are gone, the world-state system keeps working — Reactive World's hidden Holy Nation commanders, the occupied bases that change hands, the Hub rebuilding under its new ruler. Let the last act be a decision: which successor power do you back, which remnant do you hunt to extinction, which corner of the map becomes your legacy? Kenshi has no victory screen, so the conqueror's victory is the world you leave behind it — and the mods in this wave make that world worth writing about.])
 
The honest ending note is this: Kenshi ends when you decide it does. There is no credits sequence, no final boss that the game requires — there is a map that has become *yours*, and the mods of Wave 4 make the process of earning it more real at every step. The north is more dangerous because Cannibals Expanded made the cannibals formidable. The Shrieking Forest is a threat again because its bandits were expanded. The world reacts to your conquests because Reactive World gave it reactions. Your army is earned because Recruit Prisoners for Cats charges for every loyalty. And when the last leader falls and the last remnant is hunted down, the playthrough ends the way Kenshi always ends — with the world as you made it, and a New Game ready to ask what you will do differently next time. That is the conqueror's arc, and it is complete.
